name: Branch Protection

on:
  push:
    branches: [ main ]

jobs:
  deployment-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run quality checks
      run: |
        yarn lint
        yarn type-check
        yarn format:check
        
    - name: Build for production
      run: yarn build
      
    - name: Security audit
      run: yarn audit
      
    - name: Performance check
      run: |
        echo "Production build size:"
        du -sh dist/
        echo "Large files check:"
        find dist/ -type f -size +1M -exec ls -lh {} \;
        
    - name: Deploy readiness check
      run: |
        echo "✅ All checks passed - Ready for deployment!"
        echo "Build artifacts available in dist/ directory" 